//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobCircle
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminTB
    {
        public int Admin_RegId { get; set; }
        public string Admin_Name { get; set; }
        public string Admin_Address { get; set; }
        public long Admin_Phone { get; set; }
        public string Admin_Email { get; set; }
        public string Admin_Status { get; set; }
    }
}
