//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobCircle
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyTB
    {
        public int Company_RegId { get; set; }
        public string Company_Name { get; set; }
        public string Company_Address { get; set; }
        public long Company_Phone { get; set; }
        public string Comapany_Email { get; set; }
        public string Company_Website { get; set; }
        public string Comapany_Status { get; set; }
    }
}
