//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobCircle
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class JobSearch_DBEntities1 : DbContext
    {
        public JobSearch_DBEntities1()
            : base("name=JobSearch_DBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdminTB> AdminTBs { get; set; }
        public virtual DbSet<CompanyTB> CompanyTBs { get; set; }
        public virtual DbSet<JobTB> JobTBs { get; set; }
        public virtual DbSet<LoginTB> LoginTBs { get; set; }
        public virtual DbSet<UserTB> UserTBs { get; set; }
        public virtual DbSet<JobApplicationTB> JobApplicationTBs { get; set; }
    
        public virtual int Sp_CompanyJob(Nullable<int> jid, Nullable<int> cid, string cna, string jna, string jty, string jloc, Nullable<int> jvno, string jqua, string jexp, string jskl, Nullable<long> jpay, Nullable<System.DateTime> jopda, Nullable<System.DateTime> jclsda)
        {
            var jidParameter = jid.HasValue ?
                new ObjectParameter("jid", jid) :
                new ObjectParameter("jid", typeof(int));
    
            var cidParameter = cid.HasValue ?
                new ObjectParameter("cid", cid) :
                new ObjectParameter("cid", typeof(int));
    
            var cnaParameter = cna != null ?
                new ObjectParameter("cna", cna) :
                new ObjectParameter("cna", typeof(string));
    
            var jnaParameter = jna != null ?
                new ObjectParameter("jna", jna) :
                new ObjectParameter("jna", typeof(string));
    
            var jtyParameter = jty != null ?
                new ObjectParameter("jty", jty) :
                new ObjectParameter("jty", typeof(string));
    
            var jlocParameter = jloc != null ?
                new ObjectParameter("jloc", jloc) :
                new ObjectParameter("jloc", typeof(string));
    
            var jvnoParameter = jvno.HasValue ?
                new ObjectParameter("jvno", jvno) :
                new ObjectParameter("jvno", typeof(int));
    
            var jquaParameter = jqua != null ?
                new ObjectParameter("jqua", jqua) :
                new ObjectParameter("jqua", typeof(string));
    
            var jexpParameter = jexp != null ?
                new ObjectParameter("jexp", jexp) :
                new ObjectParameter("jexp", typeof(string));
    
            var jsklParameter = jskl != null ?
                new ObjectParameter("jskl", jskl) :
                new ObjectParameter("jskl", typeof(string));
    
            var jpayParameter = jpay.HasValue ?
                new ObjectParameter("jpay", jpay) :
                new ObjectParameter("jpay", typeof(long));
    
            var jopdaParameter = jopda.HasValue ?
                new ObjectParameter("jopda", jopda) :
                new ObjectParameter("jopda", typeof(System.DateTime));
    
            var jclsdaParameter = jclsda.HasValue ?
                new ObjectParameter("jclsda", jclsda) :
                new ObjectParameter("jclsda", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_CompanyJob", jidParameter, cidParameter, cnaParameter, jnaParameter, jtyParameter, jlocParameter, jvnoParameter, jquaParameter, jexpParameter, jsklParameter, jpayParameter, jopdaParameter, jclsdaParameter);
        }
    
        public virtual ObjectResult<Sp_CompanyJobDetails_Result> Sp_CompanyJobDetails()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_CompanyJobDetails_Result>("Sp_CompanyJobDetails");
        }
    
        public virtual int Sp_CompanyReg(Nullable<int> id, string na, string add, Nullable<long> ph, string em, string wb)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var naParameter = na != null ?
                new ObjectParameter("na", na) :
                new ObjectParameter("na", typeof(string));
    
            var addParameter = add != null ?
                new ObjectParameter("add", add) :
                new ObjectParameter("add", typeof(string));
    
            var phParameter = ph.HasValue ?
                new ObjectParameter("ph", ph) :
                new ObjectParameter("ph", typeof(long));
    
            var emParameter = em != null ?
                new ObjectParameter("em", em) :
                new ObjectParameter("em", typeof(string));
    
            var wbParameter = wb != null ?
                new ObjectParameter("wb", wb) :
                new ObjectParameter("wb", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_CompanyReg", idParameter, naParameter, addParameter, phParameter, emParameter, wbParameter);
        }
    
        public virtual int Sp_id(ObjectParameter id)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_id", id);
        }
    
        public virtual int Sp_jobid(ObjectParameter id)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_jobid", id);
        }
    
        public virtual int Sp_JobSearch(string qry)
        {
            var qryParameter = qry != null ?
                new ObjectParameter("qry", qry) :
                new ObjectParameter("qry", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_JobSearch", qryParameter);
        }
    
        public virtual int Sp_Logincom(Nullable<int> id, string una, string pwd)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var unaParameter = una != null ?
                new ObjectParameter("una", una) :
                new ObjectParameter("una", typeof(string));
    
            var pwdParameter = pwd != null ?
                new ObjectParameter("pwd", pwd) :
                new ObjectParameter("pwd", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_Logincom", idParameter, unaParameter, pwdParameter);
        }
    
        public virtual int Sp_LoginReg(Nullable<int> id, string una, string pwd)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var unaParameter = una != null ?
                new ObjectParameter("una", una) :
                new ObjectParameter("una", typeof(string));
    
            var pwdParameter = pwd != null ?
                new ObjectParameter("pwd", pwd) :
                new ObjectParameter("pwd", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_LoginReg", idParameter, unaParameter, pwdParameter);
        }
    
        public virtual ObjectResult<Sp_UserJobApp_Result> Sp_UserJobApp(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_UserJobApp_Result>("Sp_UserJobApp", idParameter);
        }
    
        public virtual ObjectResult<Sp_UserJobApplicatDetails_Result> Sp_UserJobApplicatDetails(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_UserJobApplicatDetails_Result>("Sp_UserJobApplicatDetails", idParameter);
        }
    
        public virtual ObjectResult<Sp_UserJobApplication_Result> Sp_UserJobApplication(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_UserJobApplication_Result>("Sp_UserJobApplication", idParameter);
        }
    
        public virtual ObjectResult<Sp_UserJobApplication1_Result> Sp_UserJobApplication1(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_UserJobApplication1_Result>("Sp_UserJobApplication1", idParameter);
        }
    
        public virtual int Sp_UserJobApply(Nullable<int> jid, Nullable<int> cid, Nullable<int> uid, string jname)
        {
            var jidParameter = jid.HasValue ?
                new ObjectParameter("jid", jid) :
                new ObjectParameter("jid", typeof(int));
    
            var cidParameter = cid.HasValue ?
                new ObjectParameter("cid", cid) :
                new ObjectParameter("cid", typeof(int));
    
            var uidParameter = uid.HasValue ?
                new ObjectParameter("uid", uid) :
                new ObjectParameter("uid", typeof(int));
    
            var jnameParameter = jname != null ?
                new ObjectParameter("jname", jname) :
                new ObjectParameter("jname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_UserJobApply", jidParameter, cidParameter, uidParameter, jnameParameter);
        }
    
        public virtual int Sp_UserLogin(string una, string pwd, ObjectParameter status, ObjectParameter id)
        {
            var unaParameter = una != null ?
                new ObjectParameter("una", una) :
                new ObjectParameter("una", typeof(string));
    
            var pwdParameter = pwd != null ?
                new ObjectParameter("pwd", pwd) :
                new ObjectParameter("pwd", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_UserLogin", unaParameter, pwdParameter, status, id);
        }
    
        public virtual ObjectResult<Sp_UserProfile_Result> Sp_UserProfile(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_UserProfile_Result>("Sp_UserProfile", idParameter);
        }
    
        public virtual int Sp_UserProfileUpdate(Nullable<int> id, string na, Nullable<int> ag, string gen, string add, string dist, string st, Nullable<long> pin, Nullable<long> ph, string em, string qua, string exp, string skl)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var naParameter = na != null ?
                new ObjectParameter("na", na) :
                new ObjectParameter("na", typeof(string));
    
            var agParameter = ag.HasValue ?
                new ObjectParameter("ag", ag) :
                new ObjectParameter("ag", typeof(int));
    
            var genParameter = gen != null ?
                new ObjectParameter("gen", gen) :
                new ObjectParameter("gen", typeof(string));
    
            var addParameter = add != null ?
                new ObjectParameter("add", add) :
                new ObjectParameter("add", typeof(string));
    
            var distParameter = dist != null ?
                new ObjectParameter("dist", dist) :
                new ObjectParameter("dist", typeof(string));
    
            var stParameter = st != null ?
                new ObjectParameter("st", st) :
                new ObjectParameter("st", typeof(string));
    
            var pinParameter = pin.HasValue ?
                new ObjectParameter("pin", pin) :
                new ObjectParameter("pin", typeof(long));
    
            var phParameter = ph.HasValue ?
                new ObjectParameter("ph", ph) :
                new ObjectParameter("ph", typeof(long));
    
            var emParameter = em != null ?
                new ObjectParameter("em", em) :
                new ObjectParameter("em", typeof(string));
    
            var quaParameter = qua != null ?
                new ObjectParameter("qua", qua) :
                new ObjectParameter("qua", typeof(string));
    
            var expParameter = exp != null ?
                new ObjectParameter("exp", exp) :
                new ObjectParameter("exp", typeof(string));
    
            var sklParameter = skl != null ?
                new ObjectParameter("skl", skl) :
                new ObjectParameter("skl", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_UserProfileUpdate", idParameter, naParameter, agParameter, genParameter, addParameter, distParameter, stParameter, pinParameter, phParameter, emParameter, quaParameter, expParameter, sklParameter);
        }
    
        public virtual int Sp_UserReg(Nullable<int> id, string na, Nullable<int> ag, string gen, string add, string dist, string st, Nullable<long> pin, Nullable<long> ph, string em, string pto, string qua, string exp, string skl, string rs)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var naParameter = na != null ?
                new ObjectParameter("na", na) :
                new ObjectParameter("na", typeof(string));
    
            var agParameter = ag.HasValue ?
                new ObjectParameter("ag", ag) :
                new ObjectParameter("ag", typeof(int));
    
            var genParameter = gen != null ?
                new ObjectParameter("gen", gen) :
                new ObjectParameter("gen", typeof(string));
    
            var addParameter = add != null ?
                new ObjectParameter("add", add) :
                new ObjectParameter("add", typeof(string));
    
            var distParameter = dist != null ?
                new ObjectParameter("dist", dist) :
                new ObjectParameter("dist", typeof(string));
    
            var stParameter = st != null ?
                new ObjectParameter("st", st) :
                new ObjectParameter("st", typeof(string));
    
            var pinParameter = pin.HasValue ?
                new ObjectParameter("pin", pin) :
                new ObjectParameter("pin", typeof(long));
    
            var phParameter = ph.HasValue ?
                new ObjectParameter("ph", ph) :
                new ObjectParameter("ph", typeof(long));
    
            var emParameter = em != null ?
                new ObjectParameter("em", em) :
                new ObjectParameter("em", typeof(string));
    
            var ptoParameter = pto != null ?
                new ObjectParameter("pto", pto) :
                new ObjectParameter("pto", typeof(string));
    
            var quaParameter = qua != null ?
                new ObjectParameter("qua", qua) :
                new ObjectParameter("qua", typeof(string));
    
            var expParameter = exp != null ?
                new ObjectParameter("exp", exp) :
                new ObjectParameter("exp", typeof(string));
    
            var sklParameter = skl != null ?
                new ObjectParameter("skl", skl) :
                new ObjectParameter("skl", typeof(string));
    
            var rsParameter = rs != null ?
                new ObjectParameter("rs", rs) :
                new ObjectParameter("rs", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_UserReg", idParameter, naParameter, agParameter, genParameter, addParameter, distParameter, stParameter, pinParameter, phParameter, emParameter, ptoParameter, quaParameter, expParameter, sklParameter, rsParameter);
        }
    
        public virtual int Sp_fileUpdate(Nullable<int> id, string pt, string rs)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var ptParameter = pt != null ?
                new ObjectParameter("pt", pt) :
                new ObjectParameter("pt", typeof(string));
    
            var rsParameter = rs != null ?
                new ObjectParameter("rs", rs) :
                new ObjectParameter("rs", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_fileUpdate", idParameter, ptParameter, rsParameter);
        }
    }
}
